language: java
jdk:
  - openjdk11
  
 branches:
   only:
     - main
 
 cache:
   directories:
     - '$HOME/.m/repository'
     - '$HOME/.gradle'

script: "./gradlew clean package"     

#1 2 7
notifications:
  email:
    recipients:
      jinipark@naver.com
      